# Generated by Django 4.0.1 on 2022-05-29 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_created_on_alter_post_updated_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='updated_on',
            new_name='published_on',
        ),
    ]
